# Generated by Django 4.1.2 on 2022-11-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Of Trainee')),
                ('technology', models.CharField(blank=True, max_length=50, null=True, verbose_name='Technology Name')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Joining')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trainer Name')),
                ('technology', models.CharField(blank=True, max_length=50, null=True, verbose_name='Technology Name')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Joining')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_training', models.CharField(blank=True, max_length=100, null=True, verbose_name='Training Name')),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='Duration In Months')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainee', verbose_name='Trainee')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainer', verbose_name='Trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
