# Generated by Django 4.1.2 on 2022-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='trainee',
        ),
        migrations.AddField(
            model_name='training',
            name='trainee',
            field=models.ManyToManyField(to='api.trainee'),
        ),
    ]
