# Generated by Django 4.1.2 on 2022-11-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_training_trainee_training_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
